spring:
  datasource:
    url: jdbc:mysql://115.159.71.166:3306/security
    username: root
    password: root
    test-while-idle: true
    validation-query: SELECT 1
  mvc:
    view:
      prefix: /
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#http:
#  multipart:
#    max-file-size: 20Mb
#    max-request-size: 20Mb
#jwt:
#  header: Authorization
#  secret: mySecret
#  expiration: 604800
#server:
#  port: 8086
#

server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO

spring:
  thymeleaf:
    cache: false